language: c

# Use full virtual machine.
dist: xenial
sudo: required

branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

os:
  - linux
  - osx

before_script:
  # Install Gobo Eiffel
  - export GOBO=$PWD
  - export MAKEFLAGS=-j2
  - travis_wait 60 bin/install.sh -v -t gcc
  - export PATH=$PATH:$GOBO/bin
  - echo `gec --version`

  # Install ISE Eiffel
  - cd $GOBO/..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ISE_PLATFORM=linux-x86-64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ISE_PLATFORM=macosx-x86-64; fi
  - curl -sSL https://www.eiffel.org/setup/install.sh | bash > eiffel.rc
  - source ./eiffel.rc
  - echo `ec -version`

env:
  - TRAVIS_GOBO_TEST_DIR=library TRAVIS_GOBO_EIFFEL=ge
  - TRAVIS_GOBO_TEST_DIR=tool TRAVIS_GOBO_EIFFEL=ge
  - TRAVIS_GOBO_TEST_DIR=library TRAVIS_GOBO_EIFFEL=ise

script:
  # Test
  - cd $GOBO/$TRAVIS_GOBO_TEST_DIR
  - travis_wait 1800 geant test_debug_$TRAVIS_GOBO_EIFFEL
